language: python
python:
- '3.6'
install:
- pip install codecov coverage requests_mock nose_parameterized
script: nosetests --with-coverage --cover-package=wdlgen
deploy:
  provider: pypi
  user: illusional
  password:
    secure: J/eqLVwwjiTvYWvWI4x2DURRRbwYeoybfZ2ktzaaPJhkJXmDORNVOGr0u1S9Z7PpdUNzmW1TfxNrTJiOqe0eRt/leDzj5betq2972ulTswZA3SP1xjByxOIDzcfKWg8JpODo7BS6JZtw/H3KC6ZwWL9TaNilHse9qRoOtNbwZD6oUSVe/v35vuKDtSxDPBypzEkQpr5573ts6zb60/fcwpZrxp5RCqqRq9XLxRHAk154fu7e98zPwWMp2zPaHWb7fxYhB+qE1mTGvgN0opRIGvAv94GttHnUm4NZ5WjYS5PIMw2V42h3TdvSKaKQhcmbZH3IQ6+h1Ul7JsYzQqGhcmjsgPdv8rBAfbPFSb1aGVkNzN/r8ATIonakU72v3AXJqi/2vQKi9Zg1ynbzM73dk2xRrDMm6bzbrgTLtt4+icBagwhgo8S/s0f6Ib/WVbOM8Enq62DWAkoq96n8rvgj39oEMxo4bS3nzh+8XFJMsExM5lz0pG/sPYmRefplo6BmmwDU8JVQLwkyYjNxnqr2oxls0gfUoEoxDxUm4y7n7rr6buHQB6dAd1qkF9oLQ/LS2Xv0NYDlUn5wfBuVBHymV+V9aWQ0Zcwq0rcwn4ShREMrJgbptS/OXjuJKJa93yaZ9Jqt2oUYJqVsvCEO7u+mGG+dI3T3QrdJ6E6j6MrcG8I=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: illusional/python-wdlgen
